[package]
authors     = ["Nic Patterson <nic@reynn.dev>"]
description = "A general purpose version manager created in Rust 🦀."
edition     = "2018"
keywords    = ["manager"]
name        = "versm"
version     = "0.1.0"

[dependencies]
abscissa_core    = { version = "0.6.0-pre.1" }
directories-next = "2.0"
gumdrop          = "0.7"
serde            = { version = "1", features = ["serde_derive"] }
thiserror        = "1.0"

[dev-dependencies]
abscissa_core = { version = "0.6.0-pre.1", features = ["testing"] }
once_cell     = "1.2"
